### ISSUE TITLE
Top-level data source templates

### ISSUE THREAD

**Issue by Jannis** [graphprotocol/graph-node#1023]

**Comment by leodasvacas** [comment]
## Summary

Based on the discussion on https://github.com/graphprotocol/support/issues/19, and https://github.com/graphprotocol/graph-node/issues/1017, we want to move data source templates from being owned by a data source to being its own top-level field in the manifest, like this:

```
dataSources:
  - ...
templates:
  - ...
```

## Requirements

The new requirement being covered is that any data source should be able to instantiate templates declared in the `template` section, otherwise this should behave exactly like templates do today.

We need to decide on a migration path.

For graph-node we need to maitain backwards-compatibility, I suggest we do this by supporting _either_ the old form or the new form, but not a mix of both in the same manifest. We should log a deprecation warning when a subgraph uses the old form.

For graph-cli, a migration might not be a good idea, because if we simply move the nested data sources to the top level field, that might create an invalid manifest because of name conflicts. Also we haven't yet figured out how to keep yaml comments on complex migrations. To aviod a migration, we can either error or warn (which one should it be?) if the manifest uses the old form.

## Proposed Implementation

graph-cli: Implement the first step of the migration path we decide on, accept and validate top-level templates. Codegen for top-level templates. Forbid mixing the old and new forms.

graph-node: Parse the new form. Detect whether the subgraph uses the old or the new form, error if it mixes both. Make sure all data sources can access all top-level templates. Make the code as generic as possible over both forms. Add the top-level templates to the subgraph of subgraphs.

graph-ts: No change.

## Proposed Documentation Updates

- Update the subgraph manifest reference in https://github.com/graphprotocol/graph-node/blob/master/docs/subgraph-manifest.md by marking the deprecated field as such and documenting the new field.
- Update the data source templates section of the docs https://thegraph.com/docs/define-a-subgraph#data-source-templates.

## Proposed Tests / Acceptance Criteria

- Validation tests on graph-cli.
- Manual testing of graph-node functionality.

## Tasks

Task list so far:

- [ ] (1d) graph-cli: Accept, validate and do codegen for templates in the top level field.
- [ ] (0.5d) graph-cli: Forbid mixing the new and old form of templates.
- [ ] (0.5d) graph-node: Parse top-level templates.
- [ ] (1d) graph-node: Add an enum to support both forms, detect and error if they are mixed, log warning on use of the old form.
- [ ] (0.5d) graph-node: Make the runtime take a list of templates instead of directly taking `DataSource`.
- [ ] (0.5d) graph-node: Add top-level templates to the subgraph of subgraphs.

## Open questions

- We'll we do a graph-cli migration? If not, will using the current form be an error or a warning?

**Comment by leodasvacas** [comment]
@Jannis Thanks, I've updated the plan.
