### ISSUE TITLE
Cache Ethereum contract call results

### ISSUE THREAD

**Issue by Jannis** [graphprotocol/graph-node#1230]

**Comment by leoyvens** [comment]
## Rationale / Use Cases

Ethereum contract calls need to be faster, see also #827. Subgraphs such as Compound, Livepeer, Synthetix and Betoken do contract calls on most events, sometimes multiple calls per event. A call can take from 0.1s to 2s to complete. If there are hundreds of thousands of events to process, that means days of syncing time, even for minor changes to the subgraph. We're not sure how we could improve the speed of a contract call done for the first time, but if we cache the results in the DB we can have the re-syncing time drop dramatically.

## Requirements

- Calls done against block numbers considered final are cached.
- If the call is cached, we avoid `eth_call` and use the cached value.
- Access time to the cache should be about 1ms.

## Proposed User Experience

Re-syncing a subgraph without adding new contract calls should be 100x faster.

## Proposed Implementation

The call results will be cached in Postgres. Using a faster key-value storage system is left as a future improvement, using Postgres should achieve the desired requirements without complicating the operational setup. The following table is added to the database:

```
CREATE TABLE eth_call_cache (
  key bytea PRIMARY KEY,
  return_value bytea,
  accessed_at date
)
```

For the cache key I'd propose using a hash to save storage space and keep the primary key index performant. The disadvantage is that you can't tell what a call is just from inspecting the cache. The values to be hashed are: contract address + encoded function call + block number.

The day at which the entry was last used is `accessed_at`. This might be useful if the node operator finds the cache is growing too large and want to cut entries that have gone a long time without use.

## Proposed Documentation Updates

In the 'Writing Mappings -> Code Generation' section, we should note that contract calls can be slow on the first sync, but will be much faster on a re-sync.

## Proposed Tests / Acceptance Criteria

Test subgraphs that use calls on syncing and re-syncing, to make sure the cache is correct and achieves the desired speed up.

## Tasks

- [ ] (1d) graph-node: Measure sync time and impact of contract calls on a relevant subgraph.
- [ ] (2d) graph-node: Implement the cache.
- [ ] (1d) graph-node: Again measure sync time and re-sync time, check the speed up and correctness.
- [ ] (0.2d) Update docs.
- [ ] (1d) Experiment with re-syncing a large subgraph on the staging environment.

**Comment by leoyvens** [comment]
@fordN @lutter You probably have experience implemeting caches like this in SQL, so I'm interested in your thoughts, to me it seems straightforward.

**Comment by lutter** [comment]
Looks good in general. 

I would explicitly store the contract address and the block for which the call was made since they will be useful for db indexes and speeding up queries (and one day, maybe, partitioning) Maybe even store which function was called, though I assume for each `(contract address, block)` tuple, we'd only have a few entries in the cache, so that might not be that useful.

The downside of `accessed_at` is that it turns each read from the cache into a write, and therefore churn on an otherwise static table. I think we want to make the decision of whether to keep cache entries based on the contract address, i.e., nuke all cache entries for a contract. It would therefore be better to have a separate table that stores `(contract_address, accessed_at)` to reduce churn there, and we could even update it fairly infrequently, e.g., once an hour rather than on every use; it would just reduce the precision of the cleanup, but if the cleanup window is much larger than the frequency with which we update, it won't matter much.

Finally, I _think_ we have a way to see which subgraphs are using what contract address so that we can at some point translate "this subgraph is important/popular/updated a lot" to "these cache entries are valuable". If that's not the case, we should somehow track the subgraph -> cache access relationship.

**Comment by leoyvens** [comment]
Thanks for the review!

Storing the address and block number would not be a large overhead and would make the data less opaque so seems fine to me, but how would it make things faster or be a better partition key? Partitioning this seems excessive since we always access through the index. I know we'd like to achieve "shared nothing" storage between subgraphs, but this cache is meant to be shared across subgraphs.

I proposed `acessed_at` as a date so that we'd only need to update it once a day.

On most cases the subgraphs are calling contracts that appear in the metadata in some form so we could guess a relationship, but subgraphs can also bind to dynamic contract addresses which we don't store, and tracking that just so that we can be more precise when cleaning this cache seems excessive to me, at least before we get some operational experience with this.

**Comment by lutter** [comment]
> Storing the address and block number would not be a large overhead and would make the data less opaque so seems fine to me, but how would it make things faster or be a better partition key? Partitioning this seems excessive since we always access through the index. I know we'd like to achieve "shared nothing" storage between subgraphs, but this cache is meant to be shared across subgraphs.

I mentioned these things more in the vein of "these are things that are possible if we store things more explicit" rather than that they are necessarily ever needed (or even a good idea) To get started, there should absolutely only be one `eth_call_cache` table.

I understand that this data is not directly connected to an individual deployment (that's the whole point after all) 'Shared nothing' here would mean that we slice the data by contract address, which I am not suggesting we do right away, just that we have a schema that keeps that possible, similar to how we could, in theory, partition the `ehtereum_blocks` cache by network if that would ever seem useful.

> I proposed `acessed_at` as a date so that we'd only need to update it once a day.

You still need to update each cache entry individually, when the cache is really for an entire contract address. I don't think it ever makes sense to get rid of an individual cache entry, AFAICT the decision would always be on the contract address, which allows us to cut down on write traffic even more by normalizing the schema a bit without losing anything.

> On most cases the subgraphs are calling contracts that appear in the metadata in some form so we could guess a relationship, but subgraphs can also bind to dynamic contract addresses which we don't store, and tracking that just so that we can be more precise when cleaning this cache seems excessive to me, at least before we get some operational experience with this.

That makes perfect sense

**Comment by leoyvens** [comment]
After chatting with @lutter, we concluded that the DB schema should be:
```
CREATE TABLE eth_call_cache (
  key bytea PRIMARY KEY,
  return_value bytea,
  contract_address bytea
)

CREATE TABLE eth_call_meta (
   contract_address bytea PRIMARY KEY,
   accessed_at date
)
```
Normalizing `eth_call_meta` reduces the amount of updates to `accessed_at`, even if they are at most once a day per row.

**Comment by leoyvens** [comment]
A change to the plan: I think we should have the key use the block hash rather than number, so that we don't have to worry about reorgs. The question then is, do we want a separate `block` column, a separate `block_hash` column, both, or neither?
