### ISSUE TITLE
Robust execution of WASM mappings

### ISSUE THREAD

**Issue by leodasvacas** [graphprotocol/graph-node#132]
Some work items required for us to be more comfortable with executing WASM modules containing untrusted WASM in a production server:

- [x] Resetting memory between calls (https://github.com/graphprotocol/graph-node/issues/438): Assuming mappings are stateless (do not store pointers in globals), we can simply use the arena allocator and call `reset_memory` after every call to the mapping. As mentioned in comments below, we could go further and try to validate that the entire wasm memory is the same before and after an event call to enforce that they are _really_ stateless.

- [ ] Limiting the memory used by the module (https://github.com/graphprotocol/graph-node/issues/436): Instead of letting the module make it's own memory, we provide a limited memory that the module will import. `asc` has a `--importMemory` flag we can use to enable this when compiling the mapping. We can also look at parity code which does this. Or maybe we can limit the size of the default memory by checking the size when allocating. 

- [x] Special handling of panics in the runtime thread (#663). A panic is usually a reason to crash the whole node, but in the runtime it's hard to predict all the ways a potentially malicious mapping could try to trip us. So we should catch panics there and clean things up without crashing.

- [x] Runtime watchdog thread that kills mappings that run “forever” (#665). If an event handler doesn't finish in a reasonable amount of time we should detect that and kill the subgraph.

- [x] Limit maximum file size that can be fetched for IPFS (#667), to avoid having the node run out of memory.

**Comment by timmclean** [comment]
I think we'll need to do more than reset the allocator unfortunately because the mappings shouldn't be able to see left over state from previous runs, as that would lead to non-determinism

**Comment by leodasvacas** [comment]
Yes, but there you're talking about isolation between subgraphs, resetting the allocator is for clearing memory between event calls.

**Comment by timmclean** [comment]
Oops, missed getting back to you on this one.

I think there's some non-determinism still even though mappings are properly isolated from one another already. If the graph node process is run once and never restarted, then the mapping memory will stay consistent between events, but if the process is restarted, then the mapping memory will suddenly be zero'd the next time an event is handled. Basically, we don't persist the mapping memory in the store, just entity data

**Comment by lutter** [comment]
Is this still needed?

**Comment by leodasvacas** [comment]
We can close this and let #436 open on its own.
