### ISSUE TITLE
[meta] NEAR Support

### ISSUE THREAD

**Issue by maoueh** [graphprotocol/graph-node#2732]
This is a meta issue listing the actual work required to fully support NEAR inside the The Graph.

#### Depends 

- #2716 

##### Tasks

- [ ] Ensure `graph-node` is really multi-chain ready (data sources and manifest parsing/instantiation were discussed as potential missing area)
- [ ] Add basic `chain/near` package fulfilling `Blockchain` trait (will probably start with POC mappings for now, maybe just block header or even just logs as `String`).
- [ ] Ensure NEAR on StreamingFast works when block(s) are skipped.
- [ ] Discuss, finalized and implement correct mappings (stuff is still in the discussion right now about what will be available as a mapping)
- [ ] Code  generation adjustments for NEAR on [graph-cli](https://github.com/graphprotocol/graph-cli) (Does `graph-cli` requires some multi-chain love?)
- [ ] Alpha preview testing for early tester(s)
- [ ] Documentation modifications for NEAR support
- [ ] Fix all `FIXME (NEAR)` in the codebase
- [ ] Discuss and decide how hosted NEAR beta version will be operationalized
- [ ] Beta testing on hosted environment
