### ISSUE TITLE
GraphQL subscriptions

### ISSUE THREAD

**Issue by Jannis** [graphprotocol/graph-node#279]
- [x] Add entity change triggers / notification channel to Postgres https://github.com/graphprotocol/graph-node/issues/273
- [x] Generate root Subscription type in the GraphQL API schema https://github.com/graphprotocol/graph-node/issues/287
- [x] Add subscription functionality to the Store https://github.com/graphprotocol/graph-node/issues/274
- [x] Rename QueryRunner to GraphQLRunner and add support for subscriptions https://github.com/graphprotocol/graph-node/issues/276
- [x] Add subscription support to GraphQL (execution and resolvers) https://github.com/graphprotocol/graph-node/issues/275 
- [x] Add GraphQLSubscriptionServer trait and WS-based implementation https://github.com/graphprotocol/graph-node/issues/277
- [x] Implement `@entity` directive for entity types in GraphQL schema https://github.com/graphprotocol/graph-node/issues/236
