### ISSUE TITLE
[meta] SQL Pre-fetching bugfix

### ISSUE THREAD

**Issue by azf20** [graphprotocol/graph-node#2938]
- [x] Fix prefetching issue
- [x] Testing fix with production queries
- [ ] Activate pre-fetching feature flag on the Hosted Service
- [ ] Switch pre-fetching to be the default
