### ISSUE TITLE
[meta] apiVersion 0.0.6 Release

### ISSUE THREAD

**Issue by azf20** [graphprotocol/graph-node#2941]
Tracking the new apiVersion release to add #2796 and #2663 

- [x] Graph Node code complete
- [x] graph-ts code complete & release in alpha
- [x] Deal with the block cache

Hosted service: https://github.com/graphprotocol/graph-node-hosted/issues/230
- [x] Update the DB version on the Hosted Service

Other Graph Nodes: truncate the block cache automatically on startup

- [x] Deploy subgraphs using the new fields on the Hosted service
- [x] Bump the max apiVersion on the Hosted Service
- [x] Release Graph Node
- [x] Release graph-ts, graph-cli

**Comment by azf20** [comment]
This is available in graph-node:v0.25.0 ([PR](https://github.com/graphprotocol/graph-node/pull/3002)), graph-ts:v0.24.1 and graph-cli:v0.25.0
