### ISSUE TITLE
Multiple subgraph support

### ISSUE THREAD

**Issue by yanivtal** [graphprotocol/graph-node#305]
- [ ] Have an index page listing subgraphs https://github.com/graphprotocol/graph-node/issues/303
- [x] Support hosting multiple subgraphs https://github.com/graphprotocol/graph-node/issues/226
- [x] Add remove, update, list admin API commands https://github.com/graphprotocol/graph-node/issues/282
- [x] Authorization for subgraph deployment https://github.com/graphprotocol/graph-node/issues/304
- [x] Add a deploy command to the CLI graphprotocol/graph-cli#94
- [x] Watch mode for deploy command https://github.com/graphprotocol/graph-cli/issues/95

**Comment by Jannis** [comment]
@leodasvacas Now that we have an admin token, we could allow `subgraph_list` only when that token is provided.

**Comment by leodasvacas** [comment]
@Jannis agreed

**Comment by Jannis** [comment]
We've decided not to do the index page.

**Comment by leodasvacas** [comment]
Done
