### ISSUE TITLE
Block & event stream

### ISSUE THREAD

**Issue by yanivtal** [graphprotocol/graph-node#306]
- [x] Plan implementation for block and event streaming https://github.com/graphprotocol/graph-node/issues/281
- [x] Implement block ingestor component https://github.com/graphprotocol/graph-node/issues/286
- [x] Add methods to BasicStore & BlockStore for new block processing algorithm https://github.com/graphprotocol/graph-node/issues/290
- [x] Add methods to EthereumAdapter for new block processing algorithm https://github.com/graphprotocol/graph-node/issues/312
- [x] Port tim/block-processing code to feature/block-stream https://github.com/graphprotocol/tasks/issues/362
- [x] Implement stateful, resumable BlockStream based on chain head updates and subgraph IDs https://github.com/graphprotocol/graph-node/issues/372
- [x] Add Store method to transact multiple entity operations at once against a block stream https://github.com/graphprotocol/graph-node/issues/390
- [x] Generic solution for cancelling streams/futures https://github.com/graphprotocol/graph-node/issues/392
- [x] Retry web3 requests https://github.com/graphprotocol/graph-node/issues/389

**Comment by Jannis** [comment]
Summary for future development update on Medium:
> This is not a user-facing feature; however, it plays a crucial part in making The Graph reliably fetch data from Ethereum and make it available to subgraph mappings, without skipping a beat - or a block, rather. There are two sides to this: one is to ensure Ethereum blocks and their transactions and events are being fetched and cached as the chain evolves, without gaps and as fast possible. The other side is to provide each subgraph with a resumable stream of blocks, events and transactions so that the subgraph can be certain that all everything is processed in a predictable, deterministic order.

**Comment by timmclean** [comment]
@Jannis s/all everything/everything/

**Comment by Jannis** [comment]
> @Jannis s/all everything/everything/

Thanks, fixed.
