### ISSUE TITLE
Declarative state & aggregations in Graph Node

### ISSUE THREAD

**Issue by azf20** [graphprotocol/graph-node#3555]
Currently, if developers want their subgraphs to capture stateful or aggregate information, they have to fetch past state during mappings, manipulating the data by hand in Assemblyscript. This can lead to highly convoluted subgraph logic, and it can have a negative impact on performance.

This meta-issue tracks ongoing investigations & work to improve the developer experience when creating stateful & aggregating subgraphs.

- [ ] Use-case definition
- [ ] Implementation exploration
- [ ] Developer interface exploration
- [ ] Query time aggregation investigation
- [ ] Schema autogeneration considerations

## Use case definition
- State
- Totals
- Timeseries

## Reference
[Prior art](https://hackmd.io/d1XUlIOUSqulUFbtQbs0iw?view)

**Comment by 0xSkly** [comment]
what would be really awesome (and maybe completely absurd) would be something in the direction of the kafka streams api. really enjoyed working with it (when you remove all the serialization and other noise). So when you think of entities as topics and the handlers as streams ... not sure. maybe worth a thought, cause that's really what this is, data streaming. just needs a different mindset and maybe hinders adoption in comparison to the current approach which is more straight forward. 

Coming here from a completely naive place, dont know much about the internals, but wanted to add those thoughts anyways

**Comment by azf20** [comment]
Hi @0xSkly there is very active work in this area - would be great to discuss, are you in the [Discord](https://discord.gg/vtvv7FP)?

**Comment by 0xSkly** [comment]
> Hi @0xSkly there is very active work in this area - would be great to discuss, are you in the [Discord](https://discord.gg/vtvv7FP)?

Im in discord yes - skly#5234

**Comment by leoyvens** [comment]
A suggestion I have is to separate in the schema the declaration of the timeseries from the aggregations, and have it just be an immutable entity. A modification of the [working example](https://hackmd.io/d1XUlIOUSqulUFbtQbs0iw#Example):
```graphql
type Token @entity {
    id: ID!
    symbol: String!
}

# timeseries implies immutable but has the added requirement of a timestamp
type Swap @entity(immutable: true, timeseries: true) {
  id: ID!
  token: Token!
  timestamp: BigInt!
  priceUSD: BigDecimal!
  amount: BigInt!
}

# `dimension` is optional.
type TokenStats @aggregation(source:  "Swap", dimension: "token", intervals: ["hour", "day"]) {
    token: Token!
    timestamp: BigInt!
    priceUSD:  BigDecimal! @aggregate(fn: "last", arg: "priceUSD"),
    volume:    BigInt! @aggregate(fn: "sum", arg: "amount")
}
```

**Comment by lutter** [comment]
Is the main motivation for this to reduce the amount of redundantly stored data, i.e., just one `Token` id vs other attributes like `symbol` etc. ? I wonder if we could just do that behind the scenes. Otherwise, a query for time series data would look like

```graphql
query {
  token(symbol: "yo") {
    tokenStats(interval: hour, timestamp_gt: X, timestamp_lte: Y) {
      volume
    }
}
```

which is probably not terrible, either.

**Comment by leoyvens** [comment]
I wasn't thinking of nesting `tokenStats` within `token` for queries, though it's an interesting idea. My motivation is that it makes the timeseries directly queryable as any other entity, and also we don't need any special API in mappings to handle them.

I agree with having the timestamp be automatically set, we could have a directive like `timestamp: BigInt! @fromBlock` or even have it be implicitly present as a `_timestamp` field at query time.

**Comment by lutter** [comment]
> I wasn't thinking of nesting `tokenStats` within `token` for queries, though it's an interesting idea. My motivation is that it makes the timeseries directly queryable as any other entity, and also we don't need any special API in mappings to handle them.

I actually want to restrict how timeseries can be queried compared to other entities - hopefully that lets us avoid a lot of unneeded indexes. We'll see how far that can go in practice.

I think we do want a special host fn for adding to a timeseries since the semantics are different from `store.set`: for `store.set`, the expectation is that 'last call wins', i.e., when `store.set` is called multiple times within a block, whatever was used in the last call is what gets stored. For timeseries, every call to `store.add` counts: if you make three calls with a value set to 1, the sum over that value should increase by 3, not by 1. But I guess in your approach, there would never be an explicit step to add to a timeseries, it would be implicitly triggered when `Swap.save` is called. There's some ambiguity how that will interact with mutable entities - how will an update to a mutable entity change the timeseries? If a mutable entity `Thing` has a field `value`, and you build a sum over that, do we sum over all `value` values across all updates?

I would like to get to a point where something like what you suggest works, I am just not sure whether that should be the very first cut. Basically, I want to get to something that is working even if it's limited. My thought was to have something with an explicit `store.add` and then evolve that over time - not sure if we should always consider `store.add` experimental and only use it for exploration which we will expand to something like what you describe or if we should support it as a full feature.

There's another limitation with the approach you suggest as it ties a time series to one entity type; we could try and allow multiple sources for a timeseries, but I haven't thought through all the complications.

Longer term, I would love to support something like `priceUSD:  BigDecimal! @aggregate(fn: "last",  value: "Swap.amount * Boundle.priceUSD")` which would get us more to 'spreadsheet-like subgraphs', i.e., understand expressions in some limited language. I think there are design considerations that need to be tackled first, e.g., if a time series is built on `Swap`, `Mint`, and `Burn`, what would the above syntax look like? Does it even make sense to put that into the schema or will that get too unwieldy? I'd love to describe data extraction in this form, too, so that you could say 'make a Swap from this type of event provided neither it's `from` or `to` are `0x0`' But expressing conditional logic like that might become too much for the GraphQL schema and we might need to find another notation.

> I agree with having the timestamp be automatically set, we could have a directive like `timestamp: BigInt! @fromBlock` or even have it be implicitly present as a `_timestamp` field at query time.

I think we should not let people set it to anything else than the block time - I don't know what other time would be useful in this context.

**Comment by leoyvens** [comment]
> I actually want to restrict how timeseries can be queried compared to other entities

Is this really worth it? There is value in querying `Swap` in the same way as any other entity.

> There's some ambiguity how that will interact with mutable entities

Timeseries would always be immutable entities.

> multiple sources for a timeseries

In your example, how do you know which `Swap.bundle` to multiply by which `Bundle.priceUSD`? Seems like it requires some sort of join.

> 'make a Swap from this type of event provided neither it's from or to are 0x0'

This seems like something that could be expressed in a format analog to the filters we use for GraphQL queries, even if it's for an indexing time operation. This feels natural if `Swap` can be queried as any other entity.

> I think we should not let people set it to anything else than the block time

Agreed.

**Comment by leoyvens** [comment]
Another thing to discuss is what happens when querying the "current bucket", that is, the current hour or day. The proposal mentions this as a possibility in the query interface, but it doesn't describe how a query that includes the 'current' bucket is executed. I'd presume that it is executed by constructing the 'current' bucket at query time from the data points in the timeseries table.

This actually has interesting consequences for the write side. If the query side can handle partial buckets, it probably wouldn't be a big stretch for it to handle missing buckets, that is, if the hour had just passed but the rollup did not happen then the query would construct the bucket at query time. If this is possible, then the rollups can be made asynchronously. This seems favorable as it:
1. Avoids additional latency on the write side.
2. Naturally allows for bulk rollups when a subgraph is first synced.
3. Dilutes the spike in write load across subgraphs when an hour or day boundary is crossed.

**Comment by lutter** [comment]
> This actually has interesting consequences for the write side. If the query side can handle partial buckets, it probably wouldn't be a big stretch for it to handle missing buckets, that is, if the hour had just passed but the rollup did not happen then the query would construct the bucket at query time. If this is possible, then the rollups can be made asynchronously. This seems favorable as it:
> 
> 1. Avoids additional latency on the write side.
> 2. Naturally allows for bulk rollups when a subgraph is first synced.
> 3. Dilutes the spike in write load across subgraphs when an hour or day boundary is crossed.

We'll see, but I am fairly sceptical that that is the route to go: if rollups are too slow for indexing, they'll definitely be too slow to do during queries. In balance, aggregations should lower the write load as they remove a lot of intermediate writes when aggregations happen over multiple intervals as every change to the timeseries leads to a write to the hourly _and_ daily aggregations right now. I would favor an approach where rollups happen in memory during indexing, i.e., a running aggregation is maintained as the timeseries changes. The downside here is that it could require quite a bit of memory in the index node, but there's still quite a bit of room to reduce the memory requirements of entities.

I think that at some point we should look into bulk rollups during syncing; the difficulty here is to chop rollups into large chunks that are still small enough so that transactions don't run for too long (i.e., a few minutes are ok, hours are not) But in-memory rollups might be a good approach here, too.

**Comment by leoyvens** [comment]
I agree that the performance benefits of async rollups might not be significant, but still find it to be a more decoupled design. But how exactly will queries that ask for the current bucket be executed in the current proposal? That is not clear to me.

**Comment by lutter** [comment]
For the current bucket, we'll have to do the rollup at query time. My hope is that by making the default to not include the current bucket, it will only be requested fairly rarely - talking to a couple subgraph devs give me the impression that people pull in the current bucket right now mostly because it's simpler to query that way.

**Comment by lutter** [comment]
Just to log some progress, here's what remains to be done:

- [x] Review/testing of PR #5184 
- [x] Change how first/last aggregates are computed
  - define `arg_min`/`arg_max` functions in plsql
  - use them to compute `first`/`last` in `id` order
  - tell people to use auto-generated ids for timeseries (maybe find a way to enforce that) 
- [x] Change type of `timestamp` field to `Timestamp` (depends on #4758)
- [x] Support for lifetime aggregations

There's some more todo's in [the aggregation docs](https://github.com/graphprotocol/graph-node/blob/0cdfd97fabbc14c158ace252ddba0da3763abce4/docs/aggregations.md) but they can be addressed as people use aggregations and a need for them arises. The two biggest ones are probably
- [x] support for `current` in queries to get a partially filled bucket (#6293)
- [x] support for arithmetic expressions in aggregates to reduce the amount of data that needs to be stored in timeseries

**Comment by snigdha920** [comment]
> * [ ]  support for `current` in queries to get a partially filled bucket

Hi! I'm building a dashboard where I want to show a count of token transfer events over the past week. The timeseries entity is perfect for this, but with `current: ignore` by default, the data on my dashboard is always an hour old. 

I think everyone using the aggregations will face this issue. And since the information is already stored in the db, it's a shame there is no way to display it. So I'm writing to bring some more attention to this, and I would be happy to implement this feature with some guidance too. Thanks!

**Comment by lutter** [comment]
@snigdha920 The `current` issue is addressed by #6293
