### ISSUE TITLE
Separate IPFS file hosting: subgraph core files vs. arbitrary use files

### ISSUE THREAD

**Issue by fordN** [graphprotocol/graph-node#5572]
## Background
We have two major classes of files hosted on IPFS: core subgraph files (manifests, schemas, mappings) and files to be synced by subgraphs with file data sources (arbitrary user files such as images, and text documents). 

I propose we separate the storage and access points for these two classes of files in order to provide better fault separation, and to prioritize robustness of the core subgraph file hosting. 

## Proposal
Let's setup a new IPFS gateway for subgraph core files, ensure only core subgraph files are pinned and accessed via that gateway, and start to use IPFS cluster for other core devs and indexers to begin hosting these files too.  For now the arbitrary file hosting can use the existing paradigm until we redesign that setup. In the meantime at least the subgraph core file hosting will be robust and fast for network participants. 

## Tasks
- [ ] Setup new IPFS gateway for subgraph core files, located at `ipfs.network.thegraph.com/subgraphs` (just a strawman URL, let's discuss)
- [ ] Protect subgraph core IPFS with middleware and configurations that only allows subgraph core files to be pinned to it and accessed from it.
- [ ] Update graph-node to use different IPFS gateways for subgraph core objects then it does for FDS files. Needs plan. Do we supply a single IPFS gateway URL and the graph-node uses different paths for each gateway /files or /subgraphs? Or do we allow operator to supply different endpoints for each? 
- [ ] Setup IPFS cluster follow on and bring in at least one operator running a subgraph IPFS gateway.

**Comment by rotarur** [comment]
create another dedicated domain like thegraph-ipfs.com to totally separate IPFS from the main domain
