### ISSUE TITLE
IPFS robustness improvements

### ISSUE THREAD

**Issue by fordN** [graphprotocol/graph-node#5574]
```[tasklist]
### Tasks
- [ ] https://github.com/graphprotocol/graph-node/issues/5573
- [ ] https://github.com/graphprotocol/graph-node/issues/5572
- [x] Analyzing IPFS node usage + middleware implementation
```
