### ISSUE TITLE
Dynamic data sources

### ISSUE THREAD

**Issue by Jannis** [graphprotocol/graph-node#719]
# Requirements

1. Can be initiated by mappings.
2. Allows to dynamically add data sources to the subgraph at runtime.
3. Dynamic data sources are persisted and started/stopped with subgraph deployments.
4. Number of dynamic data sources is limited per subgraph.

# Proposed solution

1. Add a `templates` field to the subgraph manifest under `dataSource`:
    1. `templates` is a list of templates.
    2. Each template is a data source, with one or more fields left out (e.g. the contract address or IPFS file hash). Each of these data sources has a unique name (e.g. `ExampleDataSource`).
2. Add an API to `graph-ts` to instantiate data sources from templates on demand.
    1. Add a generic, low-level API like `subgraph.createDataSource(name: string, params: string[]): void`
    2. Generate bindings for subgraph templates via `graph codegen`. Usage example:
       ```
       import { ExampleDataSource } from './generated/templates/DataSource'
       ...
             
       ExampleDataSource.create(address)
       ```
       The parameters to `create` depend on the type of the data source template. E.g. an IPFS file data source would take an IPLD link or IPFS hash, an `ethereum/contract` data source would take just the contract address.
3. When a data source template is instantiated, add the data source to the subgraph:
   1. Write the data source to the store in the form of entities, under the corresponding subgraph deployment.
   2. Update the block stream so it
        a) Rescans the current block for events for the new data source
        b) Includes events for the new data source going forward

# Tasks

- [x] Graph CLI: Validate data sources templates in the manifest.
  - [x] Add data source templates to the subgraph manifest schema
  - [x] Validate templates based on the schema
  - [x] Validate event names in templates
  - [x] Validate invalid ABI references in templates
  - [x] Validate absence of handlers in templates
- [x] Graph CLI: Generate classes for instantiating data sources from templates.
- [x] Graph CLI: Compile and upload data source templates
  - [x] Write/upload template ABIs
  - [x] Compile/write/upload template mappings
- [x] Graph TS: Add generic data source instantiation API.
- [x] Graph Node: Parse templates in subgraph manifests.
- [x] Graph Node: Write template entities as part of the subgraph meta data.
- [x] Graph Node: Instantiate data sources by adding the data source to the subgraph entities.
- [x] Graph Node: Update the block stream to include events for the new data source from the current block and from future blocks.
- [x] Graph Node: Add an environment variable to limit the number of dynamic data sources per subgraph. Pick a reasonable default.
- [x] Docs: Add documentation for dynamic data sources

**Comment by orenyodfat** [comment]
is that address #493 ?
