### ISSUE TITLE
Big Decimal Support

### ISSUE THREAD

**Issue by davekaj** [graphprotocol/graph-node#720]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Big Ints can't return fractions, so in some cases we lose precision that we need

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Reproduction of the problem can be seen on uniswap subgraph, where we try to divide ETH price by MKR price and it returns 0 instead of `~0.270`

**What is the expected behavior?**
We get the fraction returned

I closed this issue https://github.com/graphprotocol/graph-ts/issues/34 in `graph-ts` that is related

**Comment by leodasvacas** [comment]
I agree that if you divide two BigInts you should get an exact result. Using f64 internally is a bad option since it will lose precison in intermediary operations, since this usually represents monetary values precision must be controled. So we should represent the number as a fraction.

An open question is how do we represent this in graphql? Some options:
- Return a fraction string and let frontend get as much precision as it wants.
- Approximate to an f64 so we can use the native graphql type. This gets us around 15 digits of decimal precision.
- Aproximate to a decimal string so we can get more precision than an f64, but how much is enough? 100 decimal places? Make it user configurable?

**Comment by Jannis** [comment]
I thought I had written my thoughts down somewhere else already...

* [bignumber.js](https://github.com/MikeMcl/bignumber.js/) supports fractional numbers. I'd expect Web3 clients to use this library to deal with those numbers.

* The only way to guarantee any level of precision beyond what f64 etc. are capable of is to use strings. It seems natural to me to add a `BigDecimal` (or similarly named) scalar to our GraphQL API and (de)serialize it as strings.

* According to http://www.postgresqltutorial.com/postgresql-numeric/, "[t]he NUMERIC value can have up to 131,072 digits before the decimal point 16,383 digits after the decimal point". So on the database side that should be more than sufficient.

**Comment by leodasvacas** [comment]
NUMERIC would be an easily implementable way to deal with this in the database, but we have to pick a precison and there's always a loss compared to using fractions, which are slower but exact. For fractions we'd need to find [an implementation](https://github.com/begriffs/pg_rational) or implement ourselves. The concern with losing intermediate precision is that when doing aggregations and any other arithmetic on the stored data, we'll need to consider the numerical stability of the algorithm.

Using a decimal string in graphql is an option but the open question there is how many decimal places do we want?

**Comment by leodasvacas** [comment]
I talked about this with @jacksonblazensky and he agreed that losing precison can be an issue for guaranteeing correct results aggregations, and that it would be best to represent this with fractions in the db.

**Comment by davekaj** [comment]
yeah, I agree with that. Storing it as a fraction would be fine. Even as a big string fraction. Then whoever is calling the API can convert it in the front end to a real number. 

I agree the DB can't be losing any precision because then we dont have the same results as the blockchain. but right now our fractions are rounding down to 0, and whole integers, so if we fix this my allowing huge fractional big ints , I think it would solve our problem completely

**Comment by leodasvacas** [comment]
That's an interesting idea. Instead of going for a full-fledged fraction representation that would allow arithmetic sorting and filtering, we could just store it as a string for now, this would make the implementation much easier since how to do fractions in postgres is the big open implementation question. @lutter @fordN do you guys have ideas here? I could only find [this](https://github.com/begriffs/pg_rational) and [this](https://github.com/dvarrazzo/pgmp/tree/master/src) implementations of fractions for PG, none of which inspire much confidence.

Separate note, Vyper supports a [decimal](https://viper.readthedocs.io/en/latest/types.html#decimals) type which has 10 digits of fixed precision. That's less precise than an `f64`, but fixed precision operations are easier to reason about than floating point.

**Comment by lutter** [comment]
@leodasvacas you are right that these two extensions look a bit sketchy; the first looks a little better, but it seems that it's not maintained anymore.

We also have the added difficulty that we store all our data in JSON, and that doesn't have a notion of rationals either. We might very well have to do all the handling of fractions application-side, and encode fractions into JSON following some convention (like separately as numerator/denominator, with fun stuff like bringing those fractions into lowest terms, worrying about int overflow etc.)

Storing fractions as numerator/denominator, when compared to a native fraction support, mostly has the disadvantage of making it very heard to use fractions in query conditions (like "give me everything with amount < 14/3", or "order by amount desc") We could support that by also storing a fixed-point approximation with fractions.

But looking at the [Solidity docs](https://solidity.readthedocs.io/en/latest/types.html#fixed-point-numbers), it looks like Solidity doesn't have support for fractions either, only for fixed point numbers, which Postgres supports as the `NUMERIC` type, which is much wider than what Solidity needs; we could use some `NUMERIC(M,N)`, but that's more an optimization.

I think we should just go with `NUMERIC`, since that is all that Solidity offers; using fractions would be exact, but since Solidity is inexact, I am not sure we should deviate from that. The other thing to worry about is that arithmetic with fixed-point numbers in the handlers is done the same way as in Solidity, including rounding modes, overflows etc.

**Comment by Jannis** [comment]
I agree with @lutter. Correctness is important but storing "58213953184128385124/28923513421892343523588132412391241" kind of fractions instead of "0.048583591230512" would be rather unpractical.

Since Postgres' numeric type supports much more accurate decimal numbers than Solidity, I think numeric + string representation in GraphQL feels like a decent solution.

Regarding correctness and provability: Can't we mandate a certain "big decimal" standard for index nodes?

**Comment by jacksonblazensky** [comment]
Some thoughts here. It seems pure fractions would be easier to reason about in a few domains.
- First is in the security model — bad people are awfully clever when it comes to number representations and there are potential attack vectors that take advantage of compounding effects on numerical imprecision (both from a control-flow manipulation angle and from misrepresentation of data in the interface).
- A second problem domain is consensus, we would hope consensus between indexing nodes wouldn’t get stuck due to disagreement over slightly different number representations or calculations yielding different results for example.
- And then another is possibly the verifiable computations domain, where if the inputs to a snark for example are blessed by inclusion in the canonical set, the program will execute and return a result and a verifiable proof of integrity. But then it may be possible for this result to be verified, even though the result may be significantly off due to compounded errors from imprecision.

**Comment by lutter** [comment]
One more thought here: _in theory_, fractions are precise, _in practice_, you will always run into situations where you can not represent the result of a computation, no matter what we do, unless we allow the storage for a number to grow without bound, which will brings its own fun exploits. With limited storage per number, there will always be a smallest positive number we can represent, and when we are asked to divide that number by 2 (or 10), we will need to decide whether that gets rounded back to that smallest number, or to 0.

We'll therefore have to find some pragmatic compromise for representing fractions, no matter what we do. And we'll have to make sure we can handle the fallout from that along the lines of what @jacksonblazensky  said (which might be as simple as completely disregarding non-integers for certain kinds of computations).

**Comment by leodasvacas** [comment]
@lutter That also goes for the fact that we store BigInts, strings and arrays without a bound on size, so it's not an issue particular to fractions.

**Comment by davekaj** [comment]
It sounds like we want to go with storing values in numeric , while also having a string representation of the fraction along side it. Is this correct?

It would be good to be able to move forward and have someone start working on implementing the solution. This is really blocking some of the math that makes BigInts flexible in subgraph calculations

**Comment by leodasvacas** [comment]
Considering that fixed-point is being adopted in blockchains, then we'd not be the only ones dealing with the concerns that @jacksonblazensky raised. I don't think supporting sorting and comparisons on fractions would be particularly hard, but it would be slow compared to fixed point. So doing fixed-point first seems reasonable, and we could also have fractions in the future if there are use cases that require arbitrary precision.

The question left would be the precision. @lutter suggests we use default `NUMERIC` which has a huge precision. But that's hard to put it in a spec. I'm fine with starting with `NUMERIC`, knowing we'll likely change it when doing a spec.

**Comment by leodasvacas** [comment]
Oh wow we support floats in the store (I was assuming we didn't). In light of this whole discussion, I suppose we should only have one type for non-integer numbers, and we should drop support for `f32` and support only a new fixed-point `BigDecimal`.

**Comment by davekaj** [comment]
We only refer to float here in `graph-ts index.ts`:
```
export enum ValueKind {
  STRING = 0,
  INT = 1,
  FLOAT = 2,
  BOOL = 3,
  ARRAY = 4,
  NULL = 5,
  BYTES = 6,
  BIGINT = 7,
}
```
But we never write any functions to handle setting or getting Float. Since no one is dependant on f32 right now, I agree with what you are saying leo, that we should stick with just BigDecimal

**Comment by leodasvacas** [comment]
Implementation plan:

In graph-node, add a `BigDecimal` scalar graphql type, with all the filters that `BigInt` has. Coerce it from input strings, ints or floats. Add a `store::Value::BigDecimal` variant, with a [bigdecimal](https://crates.io/crates/bigdecimal) as the backing implementation. Store it in the entity json as a string, casting to `::numeric` for filtering, same as we do for `BigInt`.

In graph-ts, add a `BigDecimal` class with a `BigInt` field for the digits and an `i64` for the scale (decimal expoent). Have a `from_big_int` constructor and the math operators (exported from the node). Change `BigInt` division from returning a `BigInt` to returning a `BigDecimal`.

In graph-cli, add `BigDecimal` to validation and to schema codegen.

**Comment by Jannis** [comment]
@leodasvacas The plan looks good to me! 👍

**Comment by leodasvacas** [comment]
A better organized plan:

### Requirements

- Have a fixed-point decimal type.
- Integrate that type fully with our graph-cli tool, our graph-ts library and our GraphQL schema.

### Proposed solution

- Call the type `BigDecimal`.
- Have parity with `BigInt` in graphql, with the added ability of coercing from floats.
- Use the [bigdecimal](https://crates.io/crates/bigdecimal) in the Rust implementation.
- Store it as a string in the entity json, casting to postgres `numeric` when necessary.
- In graph-ts, represent it as a class with a `BigInt` field for the digits and an `i64` for the scale (decimal expoent), with a `from_big_int` constructor, a `from_float` constructor and a `parse` function. Have same operations as `BigInt`. Change `BigInt` division from returning a `BigInt` to returning a `BigDecimal`.

### Tasks

- [ ] Graph Node: Add `BigDecimal` scalar graphql type, with appropriate filters and coercions.
- [ ] Graph Node: Add `BigDecimal` store value type, and implement its operations in the postgres store.
- [ ] Graph CLI: Add `BigDecimal` to validation and schema codegen.
- [ ] Graph TS: Implement the `BigDecimal` class and its operations.
- [ ] Graph Node: Implement runtime support for the `BigDecimal` AS class.

**Comment by Jannis** [comment]
I only have two comments about the plan (which looks great):

1. In graph-ts, the methods would be `fromBigInt(n: BigInt)` and `fromFloat(n: f64)` instead of `from_big_int` and `from_float`.

2. Changing the behavior of `div`/`/` for `BigInt` might break existing subgraphs. I also think there should be a `BigInt` division method that returns a `BigInt`. Think `5 / 4 = 1` vs. `5 / 4.0 = 1.25`. Can we check if we can overload the `/` operator so that we can do e.g.
   ```typescript
   let n: BigInt = BigInt.fromI32(5) / BigInt.fromI32(4) // => 1 (as BigInt)
   let f: BigDecimal = BigInt.fromI32(5) / BigDecimal.fromBigInt(BigInt.fromI32(4)) // => 1.25 (as BigDecimal)
   ```
   That would be ideal. If we can't do that, I'm ok if we break the behavior.

**Comment by Jannis** [comment]
I touched base with the AS team regarding operator overloading. It's not currently possible.

**Comment by leodasvacas** [comment]
Thanks for the comments! That's not possible even in Rust so I'm not surprised. Different languages take different approaches with division of integers. Since JS/TS/AS will return a float, it seems reasonable to follow the convention. We should offer a `asBigInt()` to truncate the `BigDecimal`.
