### ISSUE TITLE
GraphQL interface fragments

### ISSUE THREAD

**Issue by Jannis** [graphprotocol/graph-node#771]

**Comment by leodasvacas** [comment]
## Rationale

This is about [GraphQL fragments](https://graphql.github.io/graphql-spec/draft/#sec-Language.Fragments), users need them so that they can query interfaces for fields that only exist in some types.

## Requirements

It turns out that this already works (not sure exactly how) for non-inline fragments, that should be tested. Inline fragments should also work.

## Proposed User Experience

This should work as in any other graphql implementation.
    
## Proposed Implementation
    
This will be implemented in graph-node. It should only affect the graphql crate, specifically field collection is missing support for inline fragments.

## Proposed Documentation Updates

We currently don't have any of our own documentation for interfaces. I don't know to which extend we should write our own docs for standard graphql features.
    
## Proposed Tests / Acceptance Criteria
    
We need to add tests for querying interfaces with fragments, first with regular fragments (which work but are untested) and then for inline fragments.

## Tasks
    
- [ ] (0.5d) graph-node: Add tests for non-inline fragments
- [ ] (0.5d) graph-node: Review current implementation
- [ ] (1d) graph-node: Implement inline fragments and add tests for them
